yml change

diff --git a/BookShop/Angular/bookShop/.github/workflows/main.yml b/BookShop/Angular/bookShop/.github/workflows/main.yml
--- a/BookShop/Angular/bookShop/.github/workflows/main.yml
+++ b/BookShop/Angular/bookShop/.github/workflows/main.yml
@@ -12,9 +12,9 @@ jobs:
           node-version: 10.x
       - name: npm install, build
         run: |
-          npm install
+          yarn
           npm run build
       - name: run Lighthouse CI
         run: |
           npm install -g @lhci/cli@0.4.x
-          lhci autorun
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI FAILED"
